
-- SELECT PRODUCT WITH AVERAGE PRICE MORE THAN AVERAGE
SELECT PRODUCTNAME
FROM Products
WHERE UnitPrice > (
	SELECT AVG(UnitPrice)
	FROM Products
)

-- ORDER PRODUCT WITH ORDER WISE PRODUCT SHIPPED
SELECT *
FROM ORDERS
ORDER BY ShippedDate

-- LIST NAME OF COUNTRY WHERE TWO OR MORE SUPPLIERS BELONG TO
SELECT Country
FROM Suppliers
GROUP BY COUNTRY
HAVING COUNT(COUNTRY) > 1

-- DELAYED ORDERS WITH MONTH
SELECT MONTH(ShippedDate-RequiredDate) AS [MONTH NUMBER],COUNT(OrderID) AS [ORDERS DELAYED]
FROM ORDERS
GROUP BY MONTH(ShippedDate-RequiredDate)

-- SHOW DISCOUNTED ORDERS WITH DISCOUNT
SELECT OrderID,SUM(Discount) AS DISCOUNT
FROM [Order Details]
WHERE Discount <> 0
GROUP BY OrderID

-- LIST NUMBER OF ORDERS DELIVERED IN CITIES OF USA IN 1997
SELECT ShipCity , COUNT(ORDERID) AS [NO. OF ORDERS]
FROM ORDERS
WHERE ShipCountry='USA' AND YEAR(ShippedDate)=1997
GROUP BY ShipCity

-- SHOW COUNTRY WITH NUMBER OF DELAYED ORDERS
SELECT ShipCountry, COUNT(ORDERID) AS [ORDERS DELAYED]
FROM ORDERS
WHERE ShippedDate > RequiredDate
GROUP BY ShipCountry
ORDER BY [ORDERS DELAYED] DESC

-- DISCOUNTED PRODUCTS WITH TOTAL PRICE OF ORDER
SELECT OrderID,SUM(DISCOUNT) AS DISCOUNT,SUM(UNITPRICE) AS [TOTAL PRICE]
FROM [Order Details]
WHERE Discount <> 0
GROUP BY OrderID

-- SHIP REGION WITH NUMBER OF ORDERS IN 1997
SELECT ShipRegion ,ShipCity ,COUNT(ORDERID) AS ORDERS
FROM ORDERS
WHERE YEAR(ShippedDate) = 1997
GROUP BY ShipCity,ShipRegion


